### ISSUE TITLE
для фоток для ридми

### ISSUE THREAD

**Issue by ohld** [fiztehradio/missmipt#1]
вот так делается бесплатный хостинг фоток, ребята

**Comment by ohld** [comment]
![image](https://user-images.githubusercontent.com/5613295/53300004-de538500-3852-11e9-9f76-1fa758961ccd.png)

**Comment by ohld** [comment]
<img src="https://user-images.githubusercontent.com/5613295/53300004-de538500-3852-11e9-9f76-1fa758961ccd.png" width="300" height="250">

**Comment by caffeinum** [comment]
да, я уже тоже эту тему прохавал

**Comment by ohld** [comment]
так я у тебя это и спалил
